# TrustLogix dev docker image
ARG JDK_VERSION=12
FROM openjdk:${JDK_VERSION}-jdk

ARG SERVICE_PORT="8080"
ENV WORKDIR=/workspaces/tlx-api
# Maven - ref: https://github.com/carlossg/docker-maven/blob/master/openjdk-11/Dockerfile
ARG MAVEN_VERSION=3.8.6
ARG MAVEN_PROPS="-DskipTests"
ARG USER_HOME_DIR="/root"
ARG MAVEN_SHA=0ec48eb515d93f8515d4abe465570dfded6fa13a3ceb9aab8031428442d9912ec20f066b2afbf56964ffe1ceb56f80321b50db73cf77a0e2445ad0211fb8e38d
ARG MAVEN_BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries

RUN mkdir -p /usr/share/maven /usr/share/maven/ref \
  && curl -fsSL -o /tmp/apache-maven.tar.gz ${MAVEN_BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
  && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
  && rm -f /tmp/apache-maven.tar.gz \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn && mvn --version

ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"

RUN yum -y install https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo-1.9-1.x86_64.rpm \
  && sed -i 's/endpoint.com/endpointdev.com/g' /etc/yum.repos.d/endpoint.repo
RUN yum install git python3 jq -y && pip3 install awscli && git --version && java -version && mvn -version && python3 -V && aws --version

RUN curl -sL -o nodejs_repo_14.sh https://rpm.nodesource.com/setup_14.x && bash ./nodejs_repo_14.sh
RUN yum install -y nodejs && node --version
RUN npm install -g semantic-release @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/exec semantic-release/git semantic-release/release-notes-generator

#COPY . ${WORKDIR}
#WORKDIR ${WORKDIR}
#RUN pwd && ls && mvn -B package ${MAVEN_PROPS}

EXPOSE ${SERVICE_PORT}

CMD tail -f /dev/null

