# Scan:
#  docker-compose -f .devcontainer/docker-compose-sonarscanner.yml up
version: "3"

services:
  sonarscanner:
    image: sonarsource/sonar-scanner-cli
    container_name: sonar-scanner
    hostname: sonar-scanner
    mem_limit: 2g
    network_mode: host
    volumes:
      - $PWD:/usr/src
    command: sonar-scanner -Dsonar.login=${SONARQUBE_TOKEN} -Dsonar.exclusions=${SONAR_EXCLUSIONS} -Dsonar.cpd.exclusions=${SONAR_CPD_EXCLUSIONS} -Dproject.settings=./sonar-project.properties
